               development:
                 bucket: yorn-bucket
                 access_key_id: AKIAILN577XE74IA7WVQ
                 secret_access_key: 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

               test:
                 bucket: yorn-bucket
                 access_key_id: AKIAILN577XE74IA7WVQ
                 secret_access_key: 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

               production:
                 bucket: yorn-bucket
                 access_key_id: AKIAILN577XE74IA7WVQ
                 secret_access_key: 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
